name: Create Pull Request from dtopr to main

on:
  push:
    branches:
      - dtopr

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 모든 히스토리를 가져오기 위해 설정

      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.TARGET_REPO_TOKEN }}
          source_branch: dtopr
          target_branch: main
          title: "[DTO] 서버 DTO.ts파일 업데이트"
          body: "서버 DTO.ts파일 업데이트"
          draft: false
          label: update
